### ISSUE TITLE
IllegalArgumentException: Unknown os.arch aarch64

### ISSUE THREAD

**Issue by rawlingsj** [diffplug/durian-swt#20]
The Jenkins project recently enabled `spotless-maven-plugin` for Jenkinsfiles see https://github.com/jenkinsci/jenkins/pull/7834.  As a result we have started seeing errors when building on `aarch64`, `s390x` and `ppc64le`
```
Caused by: java.lang.IllegalArgumentException: Unknown os.arch s390x'.
    at com.diffplug.common.swt.os.OS.calculateNative (OS.java:147)
    at com.diffplug.common.swt.os.OS.detectPlatform (OS.java:113)
    at com.diffplug.common.swt.os.OS.detectPlatform (OS.java:120)
```
After a quick look could it be this code https://github.com/diffplug/durian-swt/blob/385d94a79949dff5ce4f76c46f10256da9aedd84/durian-swt.os/src/main/java/com/diffplug/common/swt/os/OS.java#L138-L148
that needs needs to handle extra architectures?

**Comment by nedtwigg** [comment]
Can you make the stacktrace deeper? To show where Spotless is using this library?

I ask because `durian-swt` is targeted towards SWT, which no longer produces binaries for `s390x` and `ppc64le`. We could fix the `aarch64` issue easily by just updating to the latest version of durian-swt, which has supported `aarch64` for a while.

https://github.com/diffplug/durian-swt/blob/385d94a79949dff5ce4f76c46f10256da9aedd84/durian-swt.os/src/main/java/com/diffplug/common/swt/os/Arch.java#L19-L20

Maybe we should add an `Arch.UNKNOWN`, for unknown Architectures. As long as the user never needs platform-specific artifacts like SWT UI libraries (such as for Spotless code formatter), the unknown architecture would just pass along...

**Comment by rawlingsj** [comment]
> Can you make the stacktrace deeper?

sure thing...

[jenkins_2.402.log](https://github.com/diffplug/durian-swt/files/11337694/jenkins_2.402.log)

**Comment by nedtwigg** [comment]
FYI, the fix above has been incorporated into `spotless-plugin-gradle 6.19.0` and `spotless-plugin-maven 2.37.0`.
